### ISSUE TITLE
Transfer domain ownership

### ISSUE THREAD

**Issue by bjacobel** [BowdoinOrient/bongo#21]
Bowdoin owns [bowdoinorient.com](http://bowdoinorient.com), I want it.
- [x] Email [mickey d](mailto:mwdavis@bowdoinorient.com) about making this happen
- [x] Transfer ownership to Hover account
- [x] Make sure it's paid for (see #27)
- [x] Transfer DNS to Route 53.

**Comment by bjacobel** [comment]
Worked on this for a while today - they won't transfer the domain, but they will forward the nameservers from the register.com account to S3. So tasks 2 and 3 I'm counting done, and this is a few days away from being done overall.

**Comment by tophtucker** [comment]
ugh this is all my fault, i never should've handed it over, i can't even
remember doing it, they probably drugged me

**Comment by bjacobel** [comment]
No worries, the way it's getting resolved is actually great because they're going to continue to pay for the domain and all we have to do is pay for Route53

Brian (mobile)

On Thu, Apr 23, 2015 at 9:12 AM -0700, "Toph Tucker" notifications@github.com wrote:

ugh this is all my fault, i never should've handed it over, i can't even

remember doing it, they probably drugged me

On Tue, Apr 21, 2015 at 9:17 PM Brian Jacobel notifications@github.com

wrote:

**Comment by bjacobel** [comment]
IT just re-pointed the nameservers!

```
$> for n in 1 2 ; do echo ns$n: ; for tld in com org ; do dig +noall +answer bowdoinorient.$tld ns ; done ; done
ns1:
bowdoinorient.com.  345597  IN  NS  ns-1194.awsdns-21.org.
bowdoinorient.com.  345597  IN  NS  ns-1841.awsdns-38.co.uk.
bowdoinorient.com.  345597  IN  NS  ns-446.awsdns-55.com.
bowdoinorient.com.  345597  IN  NS  ns-552.awsdns-05.net.
bowdoinorient.org.  345597  IN  NS  ns-554.awsdns-05.net.
bowdoinorient.org.  345597  IN  NS  ns-1272.awsdns-31.org.
bowdoinorient.org.  345597  IN  NS  ns-1851.awsdns-39.co.uk.
bowdoinorient.org.  345597  IN  NS  ns-457.awsdns-57.com.
ns2:
bowdoinorient.com.  345597  IN  NS  ns-1194.awsdns-21.org.
bowdoinorient.com.  345597  IN  NS  ns-1841.awsdns-38.co.uk.
bowdoinorient.com.  345597  IN  NS  ns-446.awsdns-55.com.
bowdoinorient.com.  345597  IN  NS  ns-552.awsdns-05.net.
bowdoinorient.org.  345597  IN  NS  ns-554.awsdns-05.net.
bowdoinorient.org.  345597  IN  NS  ns-1272.awsdns-31.org.
bowdoinorient.org.  345597  IN  NS  ns-1851.awsdns-39.co.uk.
bowdoinorient.org.  345597  IN  NS  ns-457.awsdns-57.com.
```
